title: AgustiOSS Metrics

name: AgustiOSS Metrics
url: 'https://agustibr.github.io'
highlighter: rouge
baseurl: '/metrics'
exclude:
 - scripts
 - "*.py"
 - update.sh
 - repos-to-include.txt
 - repos-to-exclude.txt
 - requirements.txt
 - README.md
